### ISSUE TITLE
UserLand program Static Image doesn't work.

### ISSUE THREAD

**Issue by woodey233** [robot9706/VirtualCameraDriver#10]
I've already fix this problem.And I'm here to tell my solution to those who met problem the same as me.
The original problem can be seen at the comment.

The **symptom** caused by the error is that the user-mode program has no  display.In other words, it means that clicking the .exe program results in no visible action.

The fundamental reason for causing this phenomenon is a problem with the initialization of the program.
And in the program,the initialization can devide into 2 parts.
One is the initialization of the user interface (UI), including the creation of controls, etc. (I haven't learned C# programming, I'm just interpreting based on my previous experience with using Qt,but I guess it's the same as qt).
And another is,in this program,the loading of **DLL** that provide an interface to access the device.I believe it is the main reason.

In short.when you meet something wrong with loading **DriverInterface.dll**,you can consider my solution.

The steps I followed to successfully run the entire program are as follows.

0. You need to change all of the platform to the same.In my case, I set  DriverInterface.dll,UserLand program Platform to x64.

1. Build the Driver project(VirtualCameraDriver-master\Driver\avshws).You need VS  and WDK(or maybe windows SDK).There are lots of guidance if you google how to install VS and WDK.When compiling, you may meet some errors.I think most of common error is about warning and signing.When you meet "warnings regard as errors",just google error info,and you will find solution(just edit propertied not to regard as errors).And you need to change signing see here ( #9 ).

2. Generate **DriverInterface**.dll.In UserLand project(VirtualCameraDriver-master\UserLand),you need to generate DLL first.And you need to choose platform.In my case, it's x64.

3. copy the dll you generate to the output folder of UserLand program.In my case, it's "VirtualCameraDriver-master\UserLand\UserDriverStaticImage\bin\Release".

4. Build UserLand program you want.Then run the exe, and you can use it.

**Comment by woodey233** [comment]
Origin issue:
I've successfully install Driver.It works.
But when i run the C# program,it shows nothing.I guess there's something wrong with it.Because there's no error messagebox.

Now I've know errors occur on the this function.
`DriverInterface.Init()`
Error Type:System.BadImageFormatException
Error Info: try to load incorrect format program.(HRESULT:0x8007000B)
It seems that the program can't load DriverInterface.dll.

And when i debug,i've seen the error about loading DriverInterface.dll.Where should i place this file into C# project after build Interface project?

Do you have any ideas?Or can you give me some advice?
 
System i use : win11 (10.0.22631 version 22631)
IDE i use: VS2022 Community

Thanks.

**Comment by woodey233** [comment]
By the way, can project properties be set (such as dependencies? I am not very familiar with the rules of C# generation) to avoid the need to copy the DLL to the exe generation directory of UserLand?Or just add this compilation information in the readme.

If this issue is resolved, I believe it will be the best project transformation I have ever seen regarding avshws(Although, in my opinion, it already is).I mean, for those who are just getting started with avstream, it will be a very time-saving project and it will also be a very good educational resource.

**Comment by robot9706** [comment]
I don't really remember how the build works. But the UserDriverStaticImage should reference the DriverInterfaceWrapper project so that gets copied after build. I'm not really sure about the DriverInterface native part, so you might need to copy it manually.

BadImageFormatException just means that you have mismatched C# and native bitness. You could try disabling the "Prefer 32bit" setting on the C# projects if they are set, and set the platform target to x64. Also make sure you are modifying the same configuration/platform pair that you are building.

I've originally put this project on GitHub just to have the code publicly, that's why I did not really write much documentation about how the build process works.

**Comment by woodey233** [comment]
I've fixed all of the problems.Don't worry about the previous comments.I'here just posting my building experience for those who meet problems.
You mean  your original intention was only to publish code and not to build an open-source project?
If in that case, I think you can simply modify the content of the README.

Just add 3 points:

When building Driver,modify signing method to sha256.
When building all of the project,don't forget to set the program to the same(all x64,etc).
When running exe program,copy DriverInterface.dll to .exe program folder.


By the way,I think this is a very good project.Thanks for your work.
