### ISSUE TITLE
Does it support Media Foundation?

### ISSUE THREAD

**Issue by woodey233** [robot9706/VirtualCameraDriver#11]
Sorry for disturb you again.I'm going to ask another question: does it support media foundation?
I think the answer is yes,right?
Though I haven't done enough tests.I've just used chrome to capture cam.Have you done other tests?

Thanks.

**Comment by robot9706** [comment]
I have only tested it with video chat programs, no idea what interface they use.
So I can't answer your question.

**Comment by woodey233** [comment]
I've test some software.
Skype(using UWP),
Chrome Browser(using media foundation default),
Zoom(maybe directShow or media foudation),
some other  conference software.
All of these about works fine.

I'll update my test here,is that ok?
