### ISSUE TITLE
Unable to init DriverInterface!

### ISSUE THREAD

**Issue by hulahulahulala** [robot9706/VirtualCameraDriver#12]
I have installed the virtual camera driver and the window test mode has been turned on. How can I confirm the problem?
![image](https://github.com/robot9706/VirtualCameraDriver/assets/50671858/594153f9-78ba-4e8f-b744-6ed6f79d3bf8)

**Comment by robot9706** [comment]
Take a look at the DeviceInterface code to see which condition fails for you. You can also try running the app with admin rights.

**Comment by hulahulahulala** [comment]
This issue ultimately appears to be a lack of VC++runtime libraries, requiring separate placement of some DLL files in exe's directory.
