### ISSUE TITLE
Thumbnail not available or black thumbnail seen

### ISSUE THREAD

**Issue by Raj123456788** [robot9706/VirtualCameraDriver#2]
Selecting driver as default camera on Teams or Zoom does not show the content preview. FYI: I am sending a video to the driver although the remote person can see the output coming from the driver but I cannot see it. if you have used teams it appears on right side corner @bottom. How can we fix it?

**Comment by robot9706** [comment]
No idea, this is just a random project if you have any issues feel free to track down and fix it :D 

I just shared my code :)
