### ISSUE TITLE
bcdedit.exe -set TESTSIGNING ON

### ISSUE THREAD

**Issue by mauleonjr** [robot9706/VirtualCameraDriver#3]
bcdedit.exe -set TESTSIGNING ON

When executing this command, either in the "RUN" of windows 10 or in the command console, it throws me the following error: 

Failed to set item data.
The value is protected by the secure boot policy and cannot be modified or deleted.

what can i do?

**Comment by robot9706** [comment]
You need to turn off secure boot in your BIOS.
