### ISSUE TITLE
Questions SetData & KeSetTimer

### ISSUE THREAD

**Issue by Raj123456788** [robot9706/VirtualCameraDriver#6]
Hello There,
I am trying to debug the driver need few things clarified:
1) HRESULT hr = propertySet->Set(GUID_PROP_CLASS, PROP_DATA_ID, NULL, 0, dataPointer, dataLength);
What API does this hit in the hwsim.cpp? it is not hitting any of my breakpoints :(
What should I do so that it hits the break points in avshws.solution

2) Is Driver continuously scanning for the data?
Any explaination is helpful. Thanks!

**Comment by robot9706** [comment]
1. SetData in filter.cpp is called when you set the data. This is defined in the DEFINE_KSPROPERTY_TABLE when the property is created.

2. A real camera (for example a USB Webcam) sends interrupts when a new picture is available, this is simulated by a timer in hwsim.cpp. The ctor creates the timer then the FakeHardware function updates the timer. The timer copies the property data from a temporary buffer to the real output buffer.

That's basically how it works.

**Comment by Raj123456788** [comment]
Hello There,
Thank you so much for the reply. I am trying to debug the driver to hit break points. Can you please send me documentation or describe in short how to debug the driver code using VS 2019. Do I need to copy  avshws.pdb to Driverstore(where .sys.inf files reside on win 10)? sincere thanks for helping!

**Comment by robot9706** [comment]
You can look it up on https://docs.microsoft.com/ there are many guides on how to debug a driver.
