### ISSUE TITLE
Can  push any video file?

### ISSUE THREAD

**Issue by kasa888** [robot9706/VirtualCameraDriver#7]
What I mean is that the driver reads the video file as a video stream

**Comment by robot9706** [comment]
Currently only bitmaps are supported.
But you can implement anything you want.

**Comment by kasa888** [comment]
Can you do it for me? I can pay for it.

**Comment by kasa888** [comment]
I am not good at developing in C   ··

**Comment by robot9706** [comment]
Nope sorry.

But why don't you decode the video and just push the frame buffer to the driver? You can do that in any language you know.

Or you could use OBS?
