### ISSUE TITLE
Compile error.  No file digest algorithm specified.

### ISSUE THREAD

**Issue by mbshqqb** [robot9706/VirtualCameraDriver#9]
No file digest algorithm specified. Please specify the digest algorithm with the /fd flag. Using /fd SHA256 is recommended and more secure than SHA1. Calling signtool with /fd sha1 is equivalent to the previous behavior. In order to select the hash algorithm used in the signing certificate's signature, use the /fd certHash option.	avshws	E:\Workspace\C++\Driver\VirtualCameraDriver-master\Driver\avshws\SIGNTASK

**Comment by mbshqqb** [comment]
using Visual Studio 2022 compiled the project, but got this problem, how to fix?

**Comment by robot9706** [comment]
Sorry no idea. I haven't tried to compile the driver with VS2022. But I'm guessing you need to change some signature settings in project settings.

**Comment by woodey233** [comment]
> using Visual Studio 2022 compiled the project, but got this problem, how to fix?

@mbshqqb just edit signing method to sha256.( properties->Driver Signing -> File Digest Algorithm )
